# Generated by Django 4.0.6 on 2022-09-04 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_useraccount_comprado_useraccount_edad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='requested_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
