# Generated by Django 4.0.6 on 2022-09-04 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_useraccount_sales_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='age_limit',
        ),
    ]
