# Generated by Django 4.0.6 on 2022-09-04 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_useraccount_age_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='age_limit',
            field=models.CharField(blank=True, choices=[('18+', '18+'), ('Age Restricted', 'Age Restricted')], max_length=14, null=True),
        ),
    ]
