# Generated by Django 4.0.6 on 2022-09-04 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_useraccount_age_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='telefon',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
