# Generated by Django 4.0.6 on 2022-09-04 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_useraccount_telefon'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='profesion',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
